services:
  pytest-exporter:
    image: pytest-exporter:latest
    build: pytest_exporter
    ports:
      - 8000:8000
    volumes:
      - /home/robbe/qcify/test_dashboard/pytest_example_data/test_results:/app/test_results
    networks:
      - testdata

  prometheus:
    image: prom/prometheus
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 3200:9090
    restart: unless-stopped
    volumes:
      - /home/robbe/qcify/test_dashboard/prometheus:/etc/prometheus
      - prom_data:/prometheus
    networks:
      - testdata
    
  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - /home/robbe/qcify/test_dashboard/grafana:/etc/grafana
    networks:
      - testdata

volumes:
  prom_data:

networks:
  testdata:
    driver: bridge
